from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class JourneyInput:
    """
    Input data required by the Travel & Risk Intelligence Engine.
    """

    starting_location: str
    exam_centre: str
    exam_date: str
    reporting_time: str
    gate_closing_time: str

    # Estimated travel duration from starting location
    # to the examination city/centre.
    estimated_travel_minutes: int

    # Local travel time from the transport hub
    # to the examination centre.
    local_travel_minutes: int = 0

    # Expected delay in the journey.
    transport_delay_minutes: int = 0

    # Optional departure time.
    # If None, the engine can calculate a recommended departure time.
    departure_time: Optional[str] = None


@dataclass
class RiskResult:
    """
    Result generated by the Travel & Risk Intelligence Engine.
    """

    expected_arrival: datetime
    reporting_time: datetime
    gate_closing_time: datetime

    buffer_minutes: int

    risk_level: str

    same_day_travel: bool

    previous_day_recommended: bool

    recommendation: str


@dataclass
class JourneyPlan:
    """
    Complete journey recommendation returned by the planner.
    """

    departure_time: datetime
    expected_arrival: datetime

    total_travel_minutes: int

    buffer_minutes: int

    risk_level: str

    same_day_travel: bool

    previous_day_recommended: bool

    recommendation: str